{"name": "Zapatillas Nike Air Zoom Winflo 5 rosa blanco mujer", "price": 76.95, "sizes": [36, 37, 38, 39, 40], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-zoom-winflo-5-rosa-blanco-mujer"}
{"name": "Zapatillas Nike Air Max Axis blanco azul marino", "price": 89.95, "sizes": [44], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-axis-blanco-azul-marino"}
{"name": "Zapatillas Nike Air Zoom Winflo 5 negro", "price": 74.9, "sizes": [42, 43, 44], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-zoom-winflo-5"}
{"name": "Zapatillas Nike Air Max Invigor Print negro beige", "price": 84.45, "sizes": [44], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-invigor-print"}
{"name": "Zapatillas Nike Air Max Axis negro blanco", "price": 84.45, "sizes": [41, 42, 44, 45], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-axis"}
{"name": "Zapatillas Nike Air Max Invigor gris claro blanco", "price": 74.95, "sizes": [38, 39, 41], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-invigor-gris-claro-blanco"}
{"name": "Zapatillas Nike Air Max Motion Racer verde marr\u00f3n", "price": 63.4, "sizes": [40, 42, 42, 44, 44, 45, 45, 46], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-racer-verde-marron"}
{"name": "Zapatillas Nike Air Max Motion Racer negro blanco gris", "price": 73.9, "sizes": [41, 42, 42, 43, 44, 44, 45, 46, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-racer-negro-blanco-gris"}
{"name": "Zapatillas Nike Air Max Motion Low SE marr\u00f3n verde mujer", "price": 60.5, "sizes": [36, 36, 37, 38, 38, 40, 40, 41], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-se-marron-verde-mujer"}
{"name": "Zapatillas Nike Air Zoom Winflo 5 negro blanco mujer", "price": 74.9, "sizes": [37, 38, 40], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-zoom-winflo-5-mujer"}
{"name": "Zapatillas Nike Air Max Kantara negro blanco", "price": 51.9, "sizes": [44, 47, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-kantara"}
{"name": "Zapatillas Nike Air Max Motion Racer gris negro blanco", "price": 63.4, "sizes": [40, 41, 42, 44, 45, 45, 46], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-racer-gris-negro-blanco"}
{"name": "Zapatillas Nike Air Max Axis negro", "price": 89.95, "sizes": [41, 42, 42, 44, 44, 45, 45], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-axis-negro"}
{"name": "Zapatillas Nike Air Max Motion Low SE negro mujer", "price": 57.6, "sizes": [38], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-se-negro-mujer"}
{"name": "Zapatillas Nike Air Max Motion Low blanco", "price": 59.4, "sizes": [45, 47, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low"}
{"name": "Zapatillas Nike Air Max Advantage negro blanco", "price": 46.1, "sizes": [47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-advantage"}
{"name": "Zapatillas Nike Air Max Kantara negro", "price": 68.8, "sizes": [44, 44, 45, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-kantara-negro"}
{"name": "Zapatillas Nike Air Max Motion Low SE negro rosa", "price": 57.6, "sizes": [40, 42, 42, 43, 44, 44, 45, 45, 46, 47, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-se"}
{"name": "Zapatillas Nike Air Max Motion Low SE gris blanco", "price": 57.6, "sizes": [40, 44, 45, 45, 46], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-se-1"}
{"name": "Zapatillas Nike Air Max Invigor negro", "price": 79.95, "sizes": [44, 45], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-invigor"}
{"name": "Zapatillas Nike Air Max Invigor blanco negro", "price": 74.95, "sizes": [44], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-invigor-blanco-negro"}
{"name": "Zapatillas Nike Air Max Invigor negro blanco", "price": 77.95, "sizes": [38, 40, 41, 42, 43, 44, 44, 45, 45, 46, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-invigor-negro-blanco"}
{"name": "Zapatillas Nike Air Max Motion Low SE azul blanco", "price": 57.6, "sizes": [42, 44, 45, 45, 46, 47, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-se-azul-blanco"}
{"name": "Zapatillas Nike Air Max Motion Low negro blanco", "price": 76.0, "sizes": [42, 44, 45, 45, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-negro-blanco"}
{"name": "Zapatillas Nike Air Max Motion Low verde blanco mujer", "price": 57.6, "sizes": [36, 36, 38, 38, 40], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-verde-blanco-mujer"}
{"name": "Zapatillas Nike Air Zoom Winflo 5 negro blanco", "price": 76.45, "sizes": [40, 42, 42, 44, 44, 45, 45], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-zoom-winflo-5-negro-blanco-turquesa"}
{"name": "Zapatillas Nike Air Max Motion Low Premium negro negro", "price": 60.5, "sizes": [42, 42, 44, 45, 45, 47], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-premium"}
{"name": "Zapatillas Nike Air Max Motion Low negro", "price": 57.6, "sizes": [45], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-1"}
{"name": "Zapatillas Nike Air Max Motion Low negro blanco mujer", "price": 57.6, "sizes": [38], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-negro-blanco-mujer"}
{"name": "Zapatillas Nike Air Max Motion Low blanco mujer", "price": 67.7, "sizes": [36, 38, 40], "store_url": "www.deporvillage.com", "item_url": "https://www.deporvillage.com/zapatillas-nike-air-max-motion-low-blanco-mujer"}
